# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qiscusrn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for qiscusrn
pod 'Firebase/Messaging'

  target 'qiscusrn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'qiscusrnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
